package main

import (
	"fmt"
	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

var colorList [][]interface{} = [][]interface{}{
	{"ColorBlack", tcell.ColorBlack},
	{"ColorMaroon", tcell.ColorMaroon},
	{"ColorGreen", tcell.ColorGreen},
	{"ColorOlive", tcell.ColorOlive},
	{"ColorNavy", tcell.ColorNavy},
	{"ColorPurple", tcell.ColorPurple},
	{"ColorTeal", tcell.ColorTeal},
	{"ColorSilver", tcell.ColorSilver},
	{"ColorGray", tcell.ColorGray},
	{"ColorRed", tcell.ColorRed},
	{"ColorLime", tcell.ColorLime},
	{"ColorYellow", tcell.ColorYellow},
	{"ColorBlue", tcell.ColorBlue},
	{"ColorFuchsia", tcell.ColorFuchsia},
	{"ColorAqua", tcell.ColorAqua},
	{"ColorWhite", tcell.ColorWhite},
	{"Color16", tcell.Color16},
	{"Color17", tcell.Color17},
	{"Color18", tcell.Color18},
	{"Color19", tcell.Color19},
	{"Color20", tcell.Color20},
	{"Color21", tcell.Color21},
	{"Color22", tcell.Color22},
	{"Color23", tcell.Color23},
	{"Color24", tcell.Color24},
	{"Color25", tcell.Color25},
	{"Color26", tcell.Color26},
	{"Color27", tcell.Color27},
	{"Color28", tcell.Color28},
	{"Color29", tcell.Color29},
	{"Color30", tcell.Color30},
	{"Color31", tcell.Color31},
	{"Color32", tcell.Color32},
	{"Color33", tcell.Color33},
	{"Color34", tcell.Color34},
	{"Color35", tcell.Color35},
	{"Color36", tcell.Color36},
	{"Color37", tcell.Color37},
	{"Color38", tcell.Color38},
	{"Color39", tcell.Color39},
	{"Color40", tcell.Color40},
	{"Color41", tcell.Color41},
	{"Color42", tcell.Color42},
	{"Color43", tcell.Color43},
	{"Color44", tcell.Color44},
	{"Color45", tcell.Color45},
	{"Color46", tcell.Color46},
	{"Color47", tcell.Color47},
	{"Color48", tcell.Color48},
	{"Color49", tcell.Color49},
	{"Color50", tcell.Color50},
	{"Color51", tcell.Color51},
	{"Color52", tcell.Color52},
	{"Color53", tcell.Color53},
	{"Color54", tcell.Color54},
	{"Color55", tcell.Color55},
	{"Color56", tcell.Color56},
	{"Color57", tcell.Color57},
	{"Color58", tcell.Color58},
	{"Color59", tcell.Color59},
	{"Color60", tcell.Color60},
	{"Color61", tcell.Color61},
	{"Color62", tcell.Color62},
	{"Color63", tcell.Color63},
	{"Color64", tcell.Color64},
	{"Color65", tcell.Color65},
	{"Color66", tcell.Color66},
	{"Color67", tcell.Color67},
	{"Color68", tcell.Color68},
	{"Color69", tcell.Color69},
	{"Color70", tcell.Color70},
	{"Color71", tcell.Color71},
	{"Color72", tcell.Color72},
	{"Color73", tcell.Color73},
	{"Color74", tcell.Color74},
	{"Color75", tcell.Color75},
	{"Color76", tcell.Color76},
	{"Color77", tcell.Color77},
	{"Color78", tcell.Color78},
	{"Color79", tcell.Color79},
	{"Color80", tcell.Color80},
	{"Color81", tcell.Color81},
	{"Color82", tcell.Color82},
	{"Color83", tcell.Color83},
	{"Color84", tcell.Color84},
	{"Color85", tcell.Color85},
	{"Color86", tcell.Color86},
	{"Color87", tcell.Color87},
	{"Color88", tcell.Color88},
	{"Color89", tcell.Color89},
	{"Color90", tcell.Color90},
	{"Color91", tcell.Color91},
	{"Color92", tcell.Color92},
	{"Color93", tcell.Color93},
	{"Color94", tcell.Color94},
	{"Color95", tcell.Color95},
	{"Color96", tcell.Color96},
	{"Color97", tcell.Color97},
	{"Color98", tcell.Color98},
	{"Color99", tcell.Color99},
	{"Color100", tcell.Color100},
	{"Color101", tcell.Color101},
	{"Color102", tcell.Color102},
	{"Color103", tcell.Color103},
	{"Color104", tcell.Color104},
	{"Color105", tcell.Color105},
	{"Color106", tcell.Color106},
	{"Color107", tcell.Color107},
	{"Color108", tcell.Color108},
	{"Color109", tcell.Color109},
	{"Color110", tcell.Color110},
	{"Color111", tcell.Color111},
	{"Color112", tcell.Color112},
	{"Color113", tcell.Color113},
	{"Color114", tcell.Color114},
	{"Color115", tcell.Color115},
	{"Color116", tcell.Color116},
	{"Color117", tcell.Color117},
	{"Color118", tcell.Color118},
	{"Color119", tcell.Color119},
	{"Color120", tcell.Color120},
	{"Color121", tcell.Color121},
	{"Color122", tcell.Color122},
	{"Color123", tcell.Color123},
	{"Color124", tcell.Color124},
	{"Color125", tcell.Color125},
	{"Color126", tcell.Color126},
	{"Color127", tcell.Color127},
	{"Color128", tcell.Color128},
	{"Color129", tcell.Color129},
	{"Color130", tcell.Color130},
	{"Color131", tcell.Color131},
	{"Color132", tcell.Color132},
	{"Color133", tcell.Color133},
	{"Color134", tcell.Color134},
	{"Color135", tcell.Color135},
	{"Color136", tcell.Color136},
	{"Color137", tcell.Color137},
	{"Color138", tcell.Color138},
	{"Color139", tcell.Color139},
	{"Color140", tcell.Color140},
	{"Color141", tcell.Color141},
	{"Color142", tcell.Color142},
	{"Color143", tcell.Color143},
	{"Color144", tcell.Color144},
	{"Color145", tcell.Color145},
	{"Color146", tcell.Color146},
	{"Color147", tcell.Color147},
	{"Color148", tcell.Color148},
	{"Color149", tcell.Color149},
	{"Color150", tcell.Color150},
	{"Color151", tcell.Color151},
	{"Color152", tcell.Color152},
	{"Color153", tcell.Color153},
	{"Color154", tcell.Color154},
	{"Color155", tcell.Color155},
	{"Color156", tcell.Color156},
	{"Color157", tcell.Color157},
	{"Color158", tcell.Color158},
	{"Color159", tcell.Color159},
	{"Color160", tcell.Color160},
	{"Color161", tcell.Color161},
	{"Color162", tcell.Color162},
	{"Color163", tcell.Color163},
	{"Color164", tcell.Color164},
	{"Color165", tcell.Color165},
	{"Color166", tcell.Color166},
	{"Color167", tcell.Color167},
	{"Color168", tcell.Color168},
	{"Color169", tcell.Color169},
	{"Color170", tcell.Color170},
	{"Color171", tcell.Color171},
	{"Color172", tcell.Color172},
	{"Color173", tcell.Color173},
	{"Color174", tcell.Color174},
	{"Color175", tcell.Color175},
	{"Color176", tcell.Color176},
	{"Color177", tcell.Color177},
	{"Color178", tcell.Color178},
	{"Color179", tcell.Color179},
	{"Color180", tcell.Color180},
	{"Color181", tcell.Color181},
	{"Color182", tcell.Color182},
	{"Color183", tcell.Color183},
	{"Color184", tcell.Color184},
	{"Color185", tcell.Color185},
	{"Color186", tcell.Color186},
	{"Color187", tcell.Color187},
	{"Color188", tcell.Color188},
	{"Color189", tcell.Color189},
	{"Color190", tcell.Color190},
	{"Color191", tcell.Color191},
	{"Color192", tcell.Color192},
	{"Color193", tcell.Color193},
	{"Color194", tcell.Color194},
	{"Color195", tcell.Color195},
	{"Color196", tcell.Color196},
	{"Color197", tcell.Color197},
	{"Color198", tcell.Color198},
	{"Color199", tcell.Color199},
	{"Color200", tcell.Color200},
	{"Color201", tcell.Color201},
	{"Color202", tcell.Color202},
	{"Color203", tcell.Color203},
	{"Color204", tcell.Color204},
	{"Color205", tcell.Color205},
	{"Color206", tcell.Color206},
	{"Color207", tcell.Color207},
	{"Color208", tcell.Color208},
	{"Color209", tcell.Color209},
	{"Color210", tcell.Color210},
	{"Color211", tcell.Color211},
	{"Color212", tcell.Color212},
	{"Color213", tcell.Color213},
	{"Color214", tcell.Color214},
	{"Color215", tcell.Color215},
	{"Color216", tcell.Color216},
	{"Color217", tcell.Color217},
	{"Color218", tcell.Color218},
	{"Color219", tcell.Color219},
	{"Color220", tcell.Color220},
	{"Color221", tcell.Color221},
	{"Color222", tcell.Color222},
	{"Color223", tcell.Color223},
	{"Color224", tcell.Color224},
	{"Color225", tcell.Color225},
	{"Color226", tcell.Color226},
	{"Color227", tcell.Color227},
	{"Color228", tcell.Color228},
	{"Color229", tcell.Color229},
	{"Color230", tcell.Color230},
	{"Color231", tcell.Color231},
	{"Color232", tcell.Color232},
	{"Color233", tcell.Color233},
	{"Color234", tcell.Color234},
	{"Color235", tcell.Color235},
	{"Color236", tcell.Color236},
	{"Color237", tcell.Color237},
	{"Color238", tcell.Color238},
	{"Color239", tcell.Color239},
	{"Color240", tcell.Color240},
	{"Color241", tcell.Color241},
	{"Color242", tcell.Color242},
	{"Color243", tcell.Color243},
	{"Color244", tcell.Color244},
	{"Color245", tcell.Color245},
	{"Color246", tcell.Color246},
	{"Color247", tcell.Color247},
	{"Color248", tcell.Color248},
	{"Color249", tcell.Color249},
	{"Color250", tcell.Color250},
	{"Color251", tcell.Color251},
	{"Color252", tcell.Color252},
	{"Color253", tcell.Color253},
	{"Color254", tcell.Color254},
	{"Color255", tcell.Color255},
	{"ColorAliceBlue", tcell.ColorAliceBlue},
	{"ColorAntiqueWhite", tcell.ColorAntiqueWhite},
	{"ColorAquaMarine", tcell.ColorAquaMarine},
	{"ColorAzure", tcell.ColorAzure},
	{"ColorBeige", tcell.ColorBeige},
	{"ColorBisque", tcell.ColorBisque},
	{"ColorBlanchedAlmond", tcell.ColorBlanchedAlmond},
	{"ColorBlueViolet", tcell.ColorBlueViolet},
	{"ColorBrown", tcell.ColorBrown},
	{"ColorBurlyWood", tcell.ColorBurlyWood},
	{"ColorCadetBlue", tcell.ColorCadetBlue},
	{"ColorChartreuse", tcell.ColorChartreuse},
	{"ColorChocolate", tcell.ColorChocolate},
	{"ColorCoral", tcell.ColorCoral},
	{"ColorCornflowerBlue", tcell.ColorCornflowerBlue},
	{"ColorCornsilk", tcell.ColorCornsilk},
	{"ColorCrimson", tcell.ColorCrimson},
	{"ColorDarkBlue", tcell.ColorDarkBlue},
	{"ColorDarkCyan", tcell.ColorDarkCyan},
	{"ColorDarkGoldenrod", tcell.ColorDarkGoldenrod},
	{"ColorDarkGray", tcell.ColorDarkGray},
	{"ColorDarkGreen", tcell.ColorDarkGreen},
	{"ColorDarkKhaki", tcell.ColorDarkKhaki},
	{"ColorDarkMagenta", tcell.ColorDarkMagenta},
	{"ColorDarkOliveGreen", tcell.ColorDarkOliveGreen},
	{"ColorDarkOrange", tcell.ColorDarkOrange},
	{"ColorDarkOrchid", tcell.ColorDarkOrchid},
	{"ColorDarkRed", tcell.ColorDarkRed},
	{"ColorDarkSalmon", tcell.ColorDarkSalmon},
	{"ColorDarkSeaGreen", tcell.ColorDarkSeaGreen},
	{"ColorDarkSlateBlue", tcell.ColorDarkSlateBlue},
	{"ColorDarkSlateGray", tcell.ColorDarkSlateGray},
	{"ColorDarkTurquoise", tcell.ColorDarkTurquoise},
	{"ColorDarkViolet", tcell.ColorDarkViolet},
	{"ColorDeepPink", tcell.ColorDeepPink},
	{"ColorDeepSkyBlue", tcell.ColorDeepSkyBlue},
	{"ColorDimGray", tcell.ColorDimGray},
	{"ColorDodgerBlue", tcell.ColorDodgerBlue},
	{"ColorFireBrick", tcell.ColorFireBrick},
	{"ColorFloralWhite", tcell.ColorFloralWhite},
	{"ColorForestGreen", tcell.ColorForestGreen},
	{"ColorGainsboro", tcell.ColorGainsboro},
	{"ColorGhostWhite", tcell.ColorGhostWhite},
	{"ColorGold", tcell.ColorGold},
	{"ColorGoldenrod", tcell.ColorGoldenrod},
	{"ColorGreenYellow", tcell.ColorGreenYellow},
	{"ColorHoneydew", tcell.ColorHoneydew},
	{"ColorHotPink", tcell.ColorHotPink},
	{"ColorIndianRed", tcell.ColorIndianRed},
	{"ColorIndigo", tcell.ColorIndigo},
	{"ColorIvory", tcell.ColorIvory},
	{"ColorKhaki", tcell.ColorKhaki},
	{"ColorLavender", tcell.ColorLavender},
	{"ColorLavenderBlush", tcell.ColorLavenderBlush},
	{"ColorLawnGreen", tcell.ColorLawnGreen},
	{"ColorLemonChiffon", tcell.ColorLemonChiffon},
	{"ColorLightBlue", tcell.ColorLightBlue},
	{"ColorLightCoral", tcell.ColorLightCoral},
	{"ColorLightCyan", tcell.ColorLightCyan},
	{"ColorLightGoldenrodYellow", tcell.ColorLightGoldenrodYellow},
	{"ColorLightGray", tcell.ColorLightGray},
	{"ColorLightGreen", tcell.ColorLightGreen},
	{"ColorLightPink", tcell.ColorLightPink},
	{"ColorLightSalmon", tcell.ColorLightSalmon},
	{"ColorLightSeaGreen", tcell.ColorLightSeaGreen},
	{"ColorLightSkyBlue", tcell.ColorLightSkyBlue},
	{"ColorLightSlateGray", tcell.ColorLightSlateGray},
	{"ColorLightSteelBlue", tcell.ColorLightSteelBlue},
	{"ColorLightYellow", tcell.ColorLightYellow},
	{"ColorLimeGreen", tcell.ColorLimeGreen},
	{"ColorLinen", tcell.ColorLinen},
	{"ColorMediumAquamarine", tcell.ColorMediumAquamarine},
	{"ColorMediumBlue", tcell.ColorMediumBlue},
	{"ColorMediumOrchid", tcell.ColorMediumOrchid},
	{"ColorMediumPurple", tcell.ColorMediumPurple},
	{"ColorMediumSeaGreen", tcell.ColorMediumSeaGreen},
	{"ColorMediumSlateBlue", tcell.ColorMediumSlateBlue},
	{"ColorMediumSpringGreen", tcell.ColorMediumSpringGreen},
	{"ColorMediumTurquoise", tcell.ColorMediumTurquoise},
	{"ColorMediumVioletRed", tcell.ColorMediumVioletRed},
	{"ColorMidnightBlue", tcell.ColorMidnightBlue},
	{"ColorMintCream", tcell.ColorMintCream},
	{"ColorMistyRose", tcell.ColorMistyRose},
	{"ColorMoccasin", tcell.ColorMoccasin},
	{"ColorNavajoWhite", tcell.ColorNavajoWhite},
	{"ColorOldLace", tcell.ColorOldLace},
	{"ColorOliveDrab", tcell.ColorOliveDrab},
	{"ColorOrange", tcell.ColorOrange},
	{"ColorOrangeRed", tcell.ColorOrangeRed},
	{"ColorOrchid", tcell.ColorOrchid},
	{"ColorPaleGoldenrod", tcell.ColorPaleGoldenrod},
	{"ColorPaleGreen", tcell.ColorPaleGreen},
	{"ColorPaleTurquoise", tcell.ColorPaleTurquoise},
	{"ColorPaleVioletRed", tcell.ColorPaleVioletRed},
	{"ColorPapayaWhip", tcell.ColorPapayaWhip},
	{"ColorPeachPuff", tcell.ColorPeachPuff},
	{"ColorPeru", tcell.ColorPeru},
	{"ColorPink", tcell.ColorPink},
	{"ColorPlum", tcell.ColorPlum},
	{"ColorPowderBlue", tcell.ColorPowderBlue},
	{"ColorRebeccaPurple", tcell.ColorRebeccaPurple},
	{"ColorRosyBrown", tcell.ColorRosyBrown},
	{"ColorRoyalBlue", tcell.ColorRoyalBlue},
	{"ColorSaddleBrown", tcell.ColorSaddleBrown},
	{"ColorSalmon", tcell.ColorSalmon},
	{"ColorSandyBrown", tcell.ColorSandyBrown},
	{"ColorSeaGreen", tcell.ColorSeaGreen},
	{"ColorSeashell", tcell.ColorSeashell},
	{"ColorSienna", tcell.ColorSienna},
	{"ColorSkyblue", tcell.ColorSkyblue},
	{"ColorSlateBlue", tcell.ColorSlateBlue},
	{"ColorSlateGray", tcell.ColorSlateGray},
	{"ColorSnow", tcell.ColorSnow},
	{"ColorSpringGreen", tcell.ColorSpringGreen},
	{"ColorSteelBlue", tcell.ColorSteelBlue},
	{"ColorTan", tcell.ColorTan},
	{"ColorThistle", tcell.ColorThistle},
	{"ColorTomato", tcell.ColorTomato},
	{"ColorTurquoise", tcell.ColorTurquoise},
	{"ColorViolet", tcell.ColorViolet},
	{"ColorWheat", tcell.ColorWheat},
	{"ColorWhiteSmoke", tcell.ColorWhiteSmoke},
	{"ColorYellowGreen", tcell.ColorYellowGreen},
}

var table = tview.NewTable().
	SetBorders(true).
	SetBordersColor(tcell.ColorBlue)

func main() {

	app := tview.NewApplication()
	//list_display()
	table_display()
	//table_display_one_line()
	if err := app.SetRoot(table, true).Run(); err != nil {
		panic(err)
	}

}

func list_display() {
	idx := 0
	cnt := len(colorList)
	for i := 0; i < cnt; i++ {
		j := 0
		x := colorList[idx]
		color_code := x[0].(string)
		color := x[1].(tcell.Color)
		table.SetCellSimple(i, j, fmt.Sprintf("code:%s", color_code))
		table.GetCell(i, j).SetBackgroundColor(color)
		idx += 1
	}
}

func table_display_one_line() {
	idx := 0
	cnt := len(colorList)
	quit := false
	for i := 0; i < cnt; i++ {
		for j := 0; i < 10; j++ {
			x := colorList[idx]
			color_code := x[0].(string)
			color := x[1].(tcell.Color)
			table.SetCellSimple(i, j, fmt.Sprintf("code:%s", color_code))
			table.GetCell(i, j).SetBackgroundColor(color)
			idx += 1
			if idx == cnt {
				quit = true
				break
			}

		}
		if quit {
			break
		}

	}

}

func table_display() {
	idx := 0
	cnt := len(colorList)
	quit := false
	for i := 0; i < 1000; i++ {
		for j := 0; j < 7; j++ {
			x := colorList[idx]
			color_code := x[0].(string)
			color := x[1].(tcell.Color)
			table.SetCellSimple(i, j, fmt.Sprintf("code:%s", color_code))
			table.GetCell(i, j).SetBackgroundColor(color)
			idx += 1
			if idx == cnt {
				quit = true
				break
			}
		}
		if quit {
			break
		}
	}
}
